name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker buildx build --platform=linux/amd64 . --file Dockerfile.coordinator --tag coordinator:v0.0.2
        docker buildx build --platform=linux/amd64 --file Dockerfile.worker --tag worker:v0.0.2 .
